language: xslt
install:
- echo "Installed"
script:
- sh .travis/publish.sh
after_success:
- sh .travis/deploy.sh
env:
  global:
  - MAP="OwlSoft/User_Guide.ditamap"
  - TITLE="OwlSoft StormCluster User Guide"
  - WELCOME="Welcome to StormCluster by OwlSoft!"
  - SKIN="oxygen"
notifications:
  email:
    on_success: always
